server:
  port: 8103

spring:
  application:
    name: day05-spring-ai-orchestration
  config:
    import: optional:classpath:application-local.yml
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen2.5:7b
          temperature: 0.2
      embedding:
        options:
          model: nomic-embed-text

demo:
  orchestration:
    startup-enabled: true
    startup-question: 用一句话介绍什么是 Spring AI
    rag:
      manual-path: classpath:data/ops_manual.txt
      top-k: 3
  ops:
    ssh:
      enabled: true
      host: 192.168.100.231
      port: 22
      username: root
      host-label: linux-231
